import { Info } from 'lucide-react'

function InfoBanner() {
  return (
    <div className="info-banner">
      <div className="info-banner-content">
        <Info size={16} className="info-banner-icon" />
        <div className="info-banner-text">
          <p className="info-banner-description">
            This dashboard monitors live operational signals generated by HR and Finance workflows. 
            Signals update automatically as internal systems process resumes, invoices, and approvals.
          </p>
        </div>
      </div>
    </div>
  )
}

export default InfoBanner
